# Generated by Django 4.2.1 on 2023-05-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.CreateModel(
            name='Booked_Bin',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('period', models.CharField(max_length=2)),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.bin')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.teacher')),
            ],
        ),
    ]
