# Generated by Django 4.2.1 on 2023-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_teacher_email_booked_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked_bin',
            old_name='bin_id',
            new_name='bin',
        ),
        migrations.RenameField(
            model_name='booked_bin',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='booked_bin',
            name='date',
            field=models.DateField(),
        ),
    ]
