# Generated by Django 4.2.1 on 2023-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_rename_bin_id_booked_bin_bin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='hi', max_length=50),
            preserve_default=False,
        ),
    ]
