# Generated by Django 4.2.1 on 2023-06-05 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_teacher_email_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_bin',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='general.bin'),
        ),
    ]
